[package]
name = "website"
version = "0.1.0"
authors = ["rhaskia <rhaskiagamedev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["rt-multi-thread"]}
tower = "0.5.2"
tower-http = { version="0.6.2", features=["fs"]}
