[application]
name = "website"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "website"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true

[web.resource]
style = ["./assets/style.css"]
script = []

[web.resource.dev]
script = []
